configuration: Release
services:
  - mssql2012sp1
branches:
  only:
    - master

before_build:
  - nuget restore EntityFramework.InterceptorEx.sln

build:
  project: EntityFramework.InterceptorEx.sln       
  verbosity: minimal
